// Controlled modal for registering a new asset.
// Tag is intentionally omitted from the form — it is auto-generated by the DB.
// Requirements: 10.4, 10.5, 10.6, 10.7

import { useState } from 'react'
import { createAsset } from '../services/assetService'
import { DuplicateSerialError } from '../types/index'
import type { Asset, AssetCategory, CreateAssetInput } from '../types/index'

// ─── Props ────────────────────────────────────────────────────────────────────

interface RegisterAssetModalProps {
  isOpen: boolean
  onClose: () => void
  onSuccess: (asset: Asset) => void
  categories: AssetCategory[]
}

// ─── Form state ───────────────────────────────────────────────────────────────

interface FormState {
  name: string
  category_id: string
  serial_number: string
  condition: string
  location: string
  is_bookable: boolean
}

const emptyForm: FormState = {
  name: '',
  category_id: '',
  serial_number: '',
  condition: '',
  location: '',
  is_bookable: false,
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function RegisterAssetModal({
  isOpen,
  onClose,
  onSuccess,
  categories,
}: RegisterAssetModalProps) {
  const [form, setForm] = useState<FormState>(emptyForm)
  const [nameError, setNameError] = useState<string | null>(null)
  const [categoryError, setCategoryError] = useState<string | null>(null)
  const [serialError, setSerialError] = useState<string | null>(null)
  const [submitError, setSubmitError] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)

  if (!isOpen) return null

  // ── Helpers ────────────────────────────────────────────────────────────────

  function handleChange(
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) {
    const { name, value, type } = e.target
    const checked = type === 'checkbox' ? (e.target as HTMLInputElement).checked : undefined
    setForm((prev) => ({ ...prev, [name]: type === 'checkbox' ? (checked ?? false) : value }))

    // Clear field-level errors on edit
    if (name === 'name') setNameError(null)
    if (name === 'category_id') setCategoryError(null)
    if (name === 'serial_number') setSerialError(null)
  }

  function validate(): boolean {
    let valid = true

    if (form.name.trim() === '') {
      setNameError('Name is required')
      valid = false
    } else if (form.name.trim().length > 255) {
      setNameError('Name must be 255 characters or fewer')
      valid = false
    }

    if (form.category_id === '') {
      setCategoryError('Category is required')
      valid = false
    }

    return valid
  }

  function resetAndClose() {
    setForm(emptyForm)
    setNameError(null)
    setCategoryError(null)
    setSerialError(null)
    setSubmitError(null)
    onClose()
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()

    if (!validate()) return

    setSubmitError(null)
    setSubmitting(true)

    const input: CreateAssetInput = {
      name: form.name.trim(),
      category_id: form.category_id,
      serial_number: form.serial_number.trim() || null,
      condition: form.condition.trim() || null,
      location: form.location.trim() || null,
      is_bookable: form.is_bookable,
    }

    try {
      const asset = await createAsset(input)
      onSuccess(asset)
      resetAndClose()
    } catch (err) {
      if (err instanceof DuplicateSerialError) {
        setSerialError('Serial number already exists')
      } else {
        setSubmitError('Something went wrong. Please try again.')
      }
    } finally {
      setSubmitting(false)
    }
  }

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="register-asset-modal-title"
      style={styles.overlay}
      onClick={(e) => {
        if (e.target === e.currentTarget) resetAndClose()
      }}
    >
      <div style={styles.modal}>
        <h3 id="register-asset-modal-title" style={styles.modalTitle}>
          Register Asset
        </h3>

        <form onSubmit={handleSubmit} noValidate>
          {/* Name — required, max 255 */}
          <div style={styles.fieldGroup}>
            <label htmlFor="asset-name" style={styles.label}>
              Name <span style={styles.required}>*</span>
            </label>
            <input
              id="asset-name"
              type="text"
              name="name"
              maxLength={255}
              value={form.name}
              onChange={handleChange}
              style={nameError ? { ...styles.input, ...styles.inputError } : styles.input}
              aria-describedby={nameError ? 'asset-name-error' : undefined}
              aria-invalid={nameError ? 'true' : 'false'}
              autoFocus
            />
            {nameError && (
              <p id="asset-name-error" style={styles.fieldError} role="alert">
                {nameError}
              </p>
            )}
          </div>

          {/* Category — required dropdown */}
          <div style={styles.fieldGroup}>
            <label htmlFor="asset-category" style={styles.label}>
              Category <span style={styles.required}>*</span>
            </label>
            <select
              id="asset-category"
              name="category_id"
              value={form.category_id}
              onChange={handleChange}
              style={
                categoryError
                  ? { ...styles.select, ...styles.inputError }
                  : styles.select
              }
              aria-describedby={categoryError ? 'asset-category-error' : undefined}
              aria-invalid={categoryError ? 'true' : 'false'}
            >
              <option value="">— Select a category —</option>
              {categories.map((cat) => (
                <option key={cat.id} value={cat.id}>
                  {cat.name}
                </option>
              ))}
            </select>
            {categoryError && (
              <p id="asset-category-error" style={styles.fieldError} role="alert">
                {categoryError}
              </p>
            )}
          </div>

          {/* Serial Number — optional */}
          <div style={styles.fieldGroup}>
            <label htmlFor="asset-serial" style={styles.label}>
              Serial Number
            </label>
            <input
              id="asset-serial"
              type="text"
              name="serial_number"
              value={form.serial_number}
              onChange={handleChange}
              style={
                serialError
                  ? { ...styles.input, ...styles.inputError }
                  : styles.input
              }
              aria-describedby={serialError ? 'asset-serial-error' : undefined}
              aria-invalid={serialError ? 'true' : 'false'}
            />
            {serialError && (
              <p id="asset-serial-error" style={styles.fieldError} role="alert">
                {serialError}
              </p>
            )}
          </div>

          {/* Condition — optional */}
          <div style={styles.fieldGroup}>
            <label htmlFor="asset-condition" style={styles.label}>
              Condition
            </label>
            <input
              id="asset-condition"
              type="text"
              name="condition"
              value={form.condition}
              onChange={handleChange}
              style={styles.input}
            />
          </div>

          {/* Location — optional */}
          <div style={styles.fieldGroup}>
            <label htmlFor="asset-location" style={styles.label}>
              Location
            </label>
            <input
              id="asset-location"
              type="text"
              name="location"
              value={form.location}
              onChange={handleChange}
              style={styles.input}
            />
          </div>

          {/* Bookable — checkbox */}
          <div style={styles.checkboxGroup}>
            <input
              id="asset-bookable"
              type="checkbox"
              name="is_bookable"
              checked={form.is_bookable}
              onChange={handleChange}
              style={styles.checkbox}
            />
            <label htmlFor="asset-bookable" style={styles.checkboxLabel}>
              Make this asset bookable (available for resource reservations)
            </label>
          </div>

          {/* Generic server-side error */}
          {submitError && (
            <p style={styles.submitError} role="alert">
              {submitError}
            </p>
          )}

          {/* Actions */}
          <div style={styles.modalActions}>
            <button
              type="button"
              style={styles.cancelButton}
              onClick={resetAndClose}
              disabled={submitting}
            >
              Cancel
            </button>
            <button
              type="submit"
              style={
                submitting
                  ? { ...styles.submitButton, opacity: 0.7 }
                  : styles.submitButton
              }
              disabled={submitting}
            >
              {submitting ? 'Saving…' : 'Register Asset'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

// ─── Inline Styles ────────────────────────────────────────────────────────────

const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  modal: {
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    padding: '1.75rem',
    width: '100%',
    maxWidth: '480px',
    boxShadow: '0 10px 25px rgba(0,0,0,0.15)',
  },
  modalTitle: {
    margin: '0 0 1.25rem',
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#111',
  },
  fieldGroup: {
    marginBottom: '1rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.3rem',
  },
  label: {
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#374151',
  },
  required: {
    color: '#dc2626',
    marginLeft: '0.15rem',
  },
  input: {
    padding: '0.5rem 0.75rem',
    fontSize: '0.9rem',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    color: '#111',
  },
  inputError: {
    borderColor: '#dc2626',
  },
  select: {
    padding: '0.5rem 0.75rem',
    fontSize: '0.9rem',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    color: '#111',
    backgroundColor: '#ffffff',
  },
  fieldError: {
    margin: 0,
    fontSize: '0.8rem',
    color: '#dc2626',
  },
  submitError: {
    margin: '0 0 0.75rem',
    padding: '0.6rem 0.75rem',
    fontSize: '0.85rem',
    color: '#dc2626',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: '6px',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '0.75rem',
    marginTop: '1.25rem',
  },
  cancelButton: {
    padding: '0.5rem 1rem',
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#374151',
    backgroundColor: '#f3f4f6',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  submitButton: {
    padding: '0.5rem 1.25rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#ffffff',
    backgroundColor: '#2563eb',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  checkboxGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  checkbox: {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
    accentColor: '#2563eb',
    flexShrink: 0,
  },
  checkboxLabel: {
    fontSize: '0.875rem',
    color: '#374151',
    cursor: 'pointer',
  },
}
